function modifyUI(x){
	return '<div id="memberModify">'
    +'<form id="memberModify">'
    +'<h2>마이페이지</h2>'
        +'<div class="container">'
            +'<hr>'
        +'<label for="member_id"><b>아이디</b></label><br>'
        +'<input type="text" name="member_id" value='+x.memberId+' readonly><br>'
        +'<label for="password"><b>비밀번호</b></label><br>'
        +'<input type="text" name="password" value=******** required><br>'
        +'<label for="name"><b>이름</b></label><br>'
        +'<input type="text" name="name" value='+x.name+' readonly><br>'
        +'<label for="ssn"><b>주민번호</b></label><br>'
        +'<input type="text" name="ssn" value='+x.ssn+' readonly><br>'
        +'<label for="address"><b>주소</b></label><br>'
        +'<input type="text"  name="address" value='+x.address+' required><br>'
        +'<label for="e_mail"><b>이메일 주소</b></label><br>'
        +'<input type="text" name="e_mail" value='+x.email+' required><br>'
        +'<label for="phone_num"><b>전화번호</b></label><br>'
        +'<input type="text" name="phone_num" value='+x.phoneNum+' required><br>'
        +'<div class="clearfix">'
        +'<button id="modify_submit_btn" class="j_button">정보수정</button><br>'
        +'<button id="delete_submit_btn" class="j_red_button">회원탈퇴</button>'
        +'</div>'
        +'</div>'
    +'</form>'
    +'</div>'
}
