function naviUI (){
	return '<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">'
    +'<a class="navbar-brand" href="#"><strong>Navbar</strong></a>'
    +'<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"'
      +'aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">'
      +'<span class="navbar-toggler-icon"></span>'
    +'</button>'
    +'<div class="collapse navbar-collapse" id="navbarSupportedContent">'
      +'<ul class="navbar-nav mr-auto">'
        +'<li class="nav-item active">'
          +'<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>'
        +'</li>'
        +'<li class="nav-item">'
          +'<a class="nav-link" href="#">Link</a>'
        +'</li>'
        +'<li class="nav-item">'
          +'<a class="nav-link" href="#">Profile</a>'
        +'</li>'
      +'</ul>'
    +'</div>'
  +'</nav>'
};