function searchUI(){
	return '<div class="container search-table">'
	+'            <div class="search-box rounded">'
	+'                <div class="row">'
	+'                    <div class="col-md-3">'
	+'					<img src="/web/resources/img/junghoon/j_tag.jpg" height="100%" width="100%" margin="5px auto"/>'
	/*+'				<button class="j_img" id="search2keyWord"><img src="/web/resources/img/junghoon/j_search.jpg" height="100%" width="100%"></button> '*/
	+'                    </div>'
	+'                    <div class="col-md-3">'
	/*+'					<img src="/web/resources/img/junghoon/j_tag.jpg" height="100%" width="100%" margin="5px auto"/>'*/
	+'					<img src="/web/resources/img/junghoon/j_search.jpg" id="tag2search" height="100%" width="100%" margin="5px auto"/>'
	+'                    </div>'
	+'            </div>'
	+'            <div class="search-list rounded">'
	                +''
	+'                <table class="table" id="myTable">'              
	+'                    <tr>'
	+'                      <br/><br/>브랜드<br/>'
	+'<div class="j_btn-group" data-toggle="buttons" >'
	+'  <div  class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> CU'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> GS25'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 한솥도시락'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary  j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 본도시락'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 세븐일레븐'
	+'  </div>&nbsp;'
	+'</div>'
	+'                    </tr>'
	+'                    <tr>'
	+'                    <br/><br/>재료&반찬<br/>'
	+'                     <div class="j_btn-group" data-toggle="buttons" >'
	+'  <div  class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 돼지고기'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 닭고기'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 소고기'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 과일&채식'
	+'  </div>&nbsp;'
	  +''
	+'</div><br/><br/>'
	+'                    </tr>'
	+'                    <tr>'
	+'                  취향<br/>'
	+'                     <div class="j_btn-group" data-toggle="buttons" >'
	+'                     <div  class="btn btn-secondary  ">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 고소'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 매콤'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 단맛'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 다이어트'
	+'  </div>&nbsp;'
	+'  <div class="btn btn-secondary j_btn">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 보양식'
	+'  </div>&nbsp;'
	                      +'</div>'
	+'                      <br/><br/>'
	+'                   </tr>'
	+'                  가격'
	+'                  <div class="slidecontainer1">'
	+'  <input type="range" min="1" max="100" value="50" class="slider" id="myRange">'
	+'<div class="row">'
	+'<button class="ss_btn">선택초기화</button>'
	+'<button class="ss_btn">검색</button>'
	+'    </div>'
	+'</div>'


	
	+'                </table>'
	+''

	+'            </div>'
	+'        </div>'
}