function searchUI(){
	return '<div class="container search-table">'
	+'            <div class="search-box rounded">'
	+'                <div class="row">'
	+'                    <div class="col-md-3">'
	+'                        <h5 class="search_title">태그로 검색</h5>'
	+'                      <button type="button" style="float:right">'
	+'                        검색어 입력하기</button>'
	                      +''
	+'                    </div>'
	+'            </div>'
	+'            <div class="search-list rounded">'
	                +''
	+'                <table class="table" id="myTable">'
	+'                    <thead>'
	+'                      <br/>상품종류<br/>'
	+'<div class="btn-group" data-toggle="buttons" >'
	+'  <label  class="btn btn-secondary btn-outline-danger rounded">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 도시락'
	+'  </label>&nbsp;'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 음료'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 라면'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 삼각김밥'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 샌드위치'
	+'  </label>'
	+'</div>'
	+'                    </thead>'
	+'                    <tr>'
	+'                      <br/><br/>브랜드<br/>'
	+'<div class="btn-group" data-toggle="buttons" >'
	+'  <label  class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> CU'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> GS25'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 한솥도시락'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 본도시락'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 세븐일레븐'
	+'  </label>'
	+'</div>'
	+'                    </tr>'
	+'                    <tr>'
	+'                    <br/><br/>재료&반찬<br/>'
	+'                     <div class="btn-group" data-toggle="buttons" >'
	+'  <label  class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 돼지고기'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 닭고기'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 소고기'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 과일&채식'
	+'  </label>'
	  +''
	+'</div><br/><br/>'
	+'                    </tr>'
	+'                    <tr>'
	+'                  취향<br/>'
	+'                     <div class="btn-group" data-toggle="buttons" >'
	+'                     <label  class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 고소'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 매콤'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 단맛'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 다이어트'
	+'  </label>'
	+'  <label class="btn btn-secondary btn-outline-danger">'
	+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 보양식'
	+'  </label>'
	                      +'</div>'
	+'                      <br/><br/>'
	+'                   </tr>'
	+'                  가격'
	+'                  <div class="slidecontainer1">'
	+'  <input type="range" min="1" max="100" value="50" class="slider" id="myRange">'
	+'<div class="row">'
	+'<button class="ss_btn">선택초기화</button>'
	+'<button class="ss_btn">검색</button>'
	+'    </div>'
	+'</div>'


	
	+'                </table>'
	+''

	+'            </div>'
	+'        </div>'
}