'<div class="container search-table" id="search_the_SachalGod">'
		+ '            <div class="search-box rounded">'
		+ '                <div class="row">'
		+ '                    <div class="col-md-3">'
		+ '					<img src="/web/resources/img/junghoon/j_search.jpg" height="100%" width="100%" margin="5px auto"/>'
		/*+'				<button class="j_img" id="search2keyWord"><img src="/web/resources/img/junghoon/j_search.jpg" height="100%" width="100%"></button> '*/
		+ '                    </div>'
		+ '                    <div class="col-md-3">'
		/*+'					<img src="/web/resources/img/junghoon/j_tag.jpg" height="100%" width="100%" margin="5px auto"/>'*/
		+ '					<img src="/web/resources/img/junghoon/j_tag.jpg" id="search2tag" height="100%" width="100%" margin="5px auto"/>'
		+ '                    </div>'
		+ '            </div>'
		+ '            <div class="search-keyword">'
		+ '           <br/><br/> '
		
		+ '<form class="form-inline md-form mr-auto mb-4">'
		+ '  <input class="j_form-control mr-sm-2"  type="text" placeholder="Search" aria-label="Search">'
		+ '  <button class="btn btn-outline-warning btn-rounded btn-sm my-0" type="submit">Search</button>'
		+ '</form>'
		
		+ '            <div>'
		+ '            <div>'
		+ '					<img src="/web/resources/img/junghoon/실검.png" id="popular_searches" height="30%" width="30%" />'
		+ '					<img src="/web/resources/img/junghoon/내연인검.png" id="myage_popular" height="30%" width="30%" margin="5px auto"/>'
		+ '            </div>'
		+ '                <ul id="popular_search_time">'
		+ '                    <li>1위 GS도시락</li>'
		+ '                    <li>2위 치킨도시락</li>'
		+ '                    <li>3위 한솥도시락</li>'
		+ '                    <li>4위 라면tep</li>'
		+ '                    <li>5위 양념치킨</li>' + '                </ul>' + ''
		+ '    </div>'

		+ '            </div>' + '        </div>'
		
		
		
		
		
		
		
		'            <div class="search-box rounded">'
		+'                <div class="row">'
		+'                    <div class="col-md-3">'
		+'					<img src="/web/resources/img/junghoon/j_tag.jpg" height="100%" width="100%" margin="5px auto"/>'
		/*+'				<button class="j_img" id="search2keyWord"><img src="/web/resources/img/junghoon/j_search.jpg" height="100%" width="100%"></button> '*/
		+'                    </div>'
		+'                    <div class="col-md-3">'
		/*+'					<img src="/web/resources/img/junghoon/j_tag.jpg" height="100%" width="100%" margin="5px auto"/>'*/
		+'					<img src="/web/resources/img/junghoon/j_search.jpg" id="tag2search" height="100%" width="100%" margin="5px auto"/>'
		+'                    </div>'
		+'            </div>'
		+'            <div class="search-list rounded">'
		                +''
		+'                <table class="table" id="myTable">'              
		+'                    <tr>'
		+'                      <br/><br/><div id="j_title_under">브랜드</div><br/>'
		+'<div class="j_btn-group" data-toggle="buttons" >'
		+'  <div  class="btn btn-danger btn-rounded j_btn">'
		+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> CU'
		+'  </div>&nbsp;'
		+'  <div class="btn btn-danger btn-rounded j_btn">'
		+'    <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> GS25'
		+'  </div>&nbsp;'
		+'  <div class="btn btn-danger btn-rounded j_btn">'
		+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 한솥도시락'
		+'  </div>&nbsp;'
		+'  <div class="btn btn-danger btn-rounded  j_btn">'
		+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 본도시락'
		+'  </div>&nbsp;'
		+'  <div class="btn btn-danger btn-rounded j_btn">'
		+'    <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 세븐일레븐'
		+'  </div>&nbsp;'
		+'</div>'
		+'                    </tr>'
		+'                    <tr>'
		+'                    <br/><br/><div id="j_title_under">재료&반찬</div><br/>'
		+'        <div class="j_btn-group" data-toggle="buttons" >'
		+'              <div  class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 닭'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 오리'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 오징어'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded  j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 소고기'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 버섯'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 김치'
		+'              </div>'
		+'              </div>'
		+'        <div class="j_btn-group" data-toggle="buttons" >'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 계란'
		+'              </div></br>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 더덕'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 새우'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 고등어'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 갈치'
		+'              </div>'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 문어'
		+'              </div>'
		+'              </div>'
		+'        <div class="j_btn-group" data-toggle="buttons" >'
		+'               <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 장어'
		+'              </div>'
		+'               <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 감자'
		+'              </div></br>'
		+'               <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 고구마'
		+'              </div>'
		+'               <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 어묵'
		+'              </div>'
		+'               <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 소시지'
		+'              </div>'
		+'                <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 돼지'
		+'              </div>'
		+'              </div>'
		+'        <div class="j_btn-group" data-toggle="buttons" >'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 치즈'
		+'              </div>'
		+'              </div>'
		+'            </div><br/><br/>'
		+'                    </tr>'
		+'                    <tr>'
		+'                  <div id="j_title_under">취향</div><br/>'
		+'                  <div class="j_btn-group" data-toggle="buttons" >'
		+'              <div  class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 고소한맛'
		+'              </div>&nbsp;'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" autocomplete="off"> 단맛'
		+'              </div>&nbsp;'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 짠맛'
		+'              </div>&nbsp;'
		+'              <div class="btn btn-danger btn-rounded  j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 달콤한맛'
		+'              </div>&nbsp;'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 매운맛'
		+'              </div>&nbsp;'
		+'              <div class="btn btn-danger btn-rounded j_btn">'
		+'                <input id="j_bbb" class="j_scbox" type="checkbox" type="" autocomplete="off"> 신맛'
		+'              </div>&nbsp;'
		+'               </div>'


		+'                      <br/><br/>'
		+'                   </tr>'
		+'                  가격'
		+'                  <div class="slidecontainer1">'
		+'  <input type="range" min="1" max="100" value="50" class="slider" id="myRange">'
		+'<div class="row">'
		+'<button class="ss_btn">선택초기화</button>'
		+'<button class="ss_btn">검색</button>'
		+'    </div>'
		+'</div>'