function y_item_listUI(x){
	return '<!-- Section: Products v.4 -->'
	+'<section class="text-center my-5">'
	+''
	+'  <!-- Grid row -->'
	+'  <div class="row">'
	+''
	+'    <!-- Grid column -->'
	+'    <div class="col-lg-2 col-md-4 mb-lg-0 mb-4">'
	+'      <!-- Collection card -->'
	+'      <div class="card collection-card z-depth-1-half">'
	+'        <!-- Card image -->'
	+'        <div class="view zoom">'
	+'          <img src="'+x.list[1].image+'" class="img-fluid" alt="">'
	+'          <div class="stripe dark">'
	+'            <a>'
	+'              <p>'+x.list[1].itemName+''
	+'                <i class="fa fa-angle-right"></i>'
	+'              </p>'
	+'            </a>'
	+'          </div>'
	+'        </div>'
	+'        <!-- Card image -->'
	+'      </div>'
	+'      <!-- Collection card -->'
	+'    </div>'
	+'    <!-- Grid column -->'
	+''
	+'    <!-- Grid column -->'
	+'    <div class="col-lg-2 col-md-6 mb-lg-0 mb-4">'
	+'      <!-- Collection card -->'
	+'      <div class="card collection-card z-depth-1-half">'
	+'        <!-- Card image -->'
	+'        <div class="view zoom">'
	+'          <img src="'+x.list[2].image+'" class="img-fluid" alt="">'
	+'          <div class="stripe light">'
	+'            <a>'
	+'              <p>'+x.list[2].itemName+''
	+'                <i class="fa fa-angle-right"></i>'
	+'              </p>'
	+'            </a>'
	+'          </div>'
	+'        </div>'
	+'        <!-- Card image -->'
	+'      </div>'
	+'      <!-- Collection card -->'
	+'    </div>'
	+'    <!-- Grid column -->'
	+''
	+'    <!-- Grid column -->'
	+'    <div class="col-lg-2 col-md-6 mb-md-0 mb-4">'
	+'      <!-- Collection card -->'
	+'      <div class="card collection-card z-depth-1-half">'
	+'        <!-- Card image -->'
	+'        <div class="view zoom">'
	+'          <img src="'+x.list[3].image+'" class="img-fluid" alt="">'
	+'          <div class="stripe dark">'
	+'            <a>'
	+'              <p>'+x.list[3].itemName+''
	+'                <i class="fa fa-angle-right"></i>'
	+'              </p>'
	+'            </a>'
	+'          </div>'
	+'        </div>'
	+'        <!-- Card image -->'
	+'      </div>'
	+'      <!-- Collection card -->'
	+'    </div>'
	+'    <!-- Grid column -->'
	+''
	+'    <!-- Fourth column -->'
	+'    <div class="col-lg-2 col-md-6">'
	+'      <!-- Collection card -->'
	+'      <div class="card collection-card z-depth-1-half">'
	+'        <!-- Card image -->'
	+'        <div class="view zoom">'
	+'          <img src="'+x.list[4].image+'" class="img-fluid" alt="">'
	+'          <div class="stripe light">'
	+'            <a>'
	+'              <p>'+x.list[4].itemName+''
	+'                <i class="fa fa-angle-right"></i>'
	+'              </p>'
	+'            </a>'
	+'          </div>'
	+'        </div>'
	+'        <!-- Card image -->'
	+'      </div>'
	+'      <!-- Collection card -->'
	+'    </div>'
	+'    <!-- Fourth column -->'
	    +''
	+'        <!-- Grid column -->'
	+'    <div class="col-lg-2 col-md-4 mb-lg-0 mb-4">'
	+'      <!-- Collection card -->'
	+'      <div class="card collection-card z-depth-1-half">'
	+'        <!-- Card image -->'
	+'        <div class="view zoom">'
	+'          <img src="'+x.list[5].image+'" class="img-fluid" alt="">'
	+'          <div class="stripe dark">'
	+'            <a>'
	+'              <p>'+x.list[5].itemName+''
	+'                <i class="fa fa-angle-right"></i>'
	+'              </p>'
	+'            </a>'
	+'          </div>'
	+'        </div>'
	+'        <!-- Card image -->'
	+'      </div>'
	+'      <!-- Collection card -->'
	+'    </div>'
	+'    <!-- Grid column -->'
	+''
	+'    <!-- Grid column -->'
	+'    <div class="col-lg-2 col-md-6 mb-lg-0 mb-4">'
	+'      <!-- Collection card -->'
	+'      <div class="card collection-card z-depth-1-half">'
	+'        <!-- Card image -->'
	+'        <div class="view zoom">'
	+'          <img src="'+x.list[6].image+'" class="img-fluid" alt="">'
	+'          <div class="stripe light">'
	+'            <a>'
	+'              <p>'+x.list[6].itemName+''
	+'                <i class="fa fa-angle-right"></i>'
	+'              </p>'
	+'            </a>'
	+'          </div>'
	+'        </div>'
	+'        <!-- Card image -->'
	+'      </div>'
	+'      <!-- Collection card -->'
	+'    </div>'
	+'    <!-- Grid column -->'
	     +''
	+''
	+''
	+'  </div>'
	+'  <!-- Grid row -->'
	+''
	+'</section>'
	+'<!-- Section: Products v.4 -->'
	
	;
}