function y_item_cLstUI(){
	return '<!--Section: Comments-->'
	+'<section class="my-5">'
	+''
	+'  <!-- Card header -->'
	+'  <div class="card-header border-0 font-weight-bold">4개의 댓글</div>'

	+'  <div class="media d-block d-md-flex mt-4">'
	+'    <img class="card-img-64 d-flex mx-auto mb-3 rounded-circle" src="/web/resources/img/yoonho/img_avatar1.png" alt="Generic placeholder image">'
	+'    <div class="media-body text-center text-md-left ml-md-3 ml-0">'
	+'      <h5 class="font-weight-bold mt-0">'
	+'        <a href="">야근</a>'
	+'      </h5>'
	+'      바쁜 저녁 마라톤회의때 먹었는데 든든합니다. 강추!!'
	+'    </div>'
	+'  </div>'
	
	+'  <div class="media d-block d-md-flex mt-3">'
	+'    <img class="card-img-64 d-flex mx-auto mb-3 rounded-circle" src="/web/resources/img/yoonho/img_avatar3.png" alt="Generic placeholder image">'
	+'    <div class="media-body text-center text-md-left ml-md-3 ml-0">'
	+'      <h5 class="font-weight-bold mt-0">'
	+'        <a href="">급식짱</a>'
	+'      </h5>'
	+'      매화도시락 너무 비싸요 음식점에서 사먹는가격보다 비쌈..'
	+'    </div>'

	+'			<a role="button" class="badge orange text-left" style="margin:10px;font-size:18px" data-toggle="modal">수정</a>'
	+'			<a role="button" class="badge orange text-left" style="margin:10px;font-size:18px" data-toggle="modal">삭제</a>'
	+'  </div>'
	
	+'  <div class="media d-block d-md-flex mt-3">'
	+'    <img class="card-img-64 d-flex mx-auto mb-3 rounded-circle" src="/web/resources/img/yoonho/img_avatar4.png" alt="Generic placeholder image">'
	+'    <div class="media-body text-center text-md-left ml-md-3 ml-0">'
	+'      <h5 class="font-weight-bold mt-0">'
	+'        <a href="">학식학식</a>'
	+'      </h5>'
	+'      윗분이야기 공감.. 학생들한테는 부담되는 가격.. 든든하긴합니다'
	+'    </div>'
	+'  </div>'
	
	+'  <div class="media d-block d-md-flex mt-3">'
	+'    <img class="card-img-64 d-flex mx-auto mb-3 rounded-circle" src="/web/resources/img/yoonho/img_avatar4.png" alt="Generic placeholder image">'
	+'    <div class="media-body text-center text-md-left ml-md-3 ml-0">'
	+'      <h5 class="font-weight-bold mt-0">'
	+'        <a href="">비트엄마</a>'
	+'      </h5>'
	+'      애기들 소풍갈때 손 많이가는데 알찬 도시락 덕에 수고를 줄였어요 ! 내용물도 알차서 든든하게 한끼 해결!'
	+'    </div>'
	+'  </div>'
	
	+''
	+'  <!--Pagination -->'
	+'  <nav class="d-flex justify-content-center mt-5">'
	+'    <ul class="pagination pg-blue mb-0">'
	+''
	+'      <!--First-->'
	+'      <li class="page-item disabled">'
	+'        <a class="page-link">First</a>'
	+'      </li>'
	+''
	+'      <!--Arrow left-->'
	+'      <li class="page-item disabled">'
	+'        <a class="page-link" aria-label="Previous">'
	+'          <span aria-hidden="true">&laquo;</span>'
	+'          <span class="sr-only">Previous</span>'
	+'        </a>'
	+'      </li>'
	+''
	+'      <!--Numbers-->'
	+'      <li class="page-item active">'
	+'        <a class="page-link">1</a>'
	+'      </li>'
	+'      <li class="page-item">'
	+'        <a class="page-link">2</a>'
	+'      </li>'
	+'      <li class="page-item">'
	+'        <a class="page-link">3</a>'
	+'      </li>'
	+'      <li class="page-item">'
	+'        <a class="page-link">4</a>'
	+'      </li>'
	+'      <li class="page-item">'
	+'        <a class="page-link">5</a>'
	+'      </li>'
	+''
	+'      <!--Arrow right-->'
	+'      <li class="page-item">'
	+'        <a class="page-link" aria-label="Next">'
	+'          <span aria-hidden="true">&raquo;</span>'
	+'          <span class="sr-only">Next</span>'
	+'        </a>'
	+'      </li>'
	+''
	+'      <!--Last-->'
	+'      <li class="page-item">'
	+'        <a class="page-link">Last</a>'
	+'      </li>'
	+''
	+'    </ul>'
	+'  </nav>'
	+'  <!--Pagination -->'
	
	+''
	+'</section>'
	+'<!--Section: Comments-->';
}
function y_item_cWrtUI(){
	return '<!--Section: Comments-->'
	+'<section class="my-5">'
	+ '      <!-- Quick Reply -->'
	+'      <div class="form-group mt-4">'
	+'        <label for="quickReplyFormComment">Your comment</label>'
	+'        <textarea class="form-control" id="quickReplyFormComment" rows="5"></textarea>'
	+''
	+'        <div class="text-center my-4">'
	+'          <button class="btn btn-primary btn-sm" type="submit">SUBMIT</button>'
	+'        </div>'
	+'      </div>'
	+'</section>'
	+'<!--Section: Comments-->';
}

function y_item_cMdfUI(){
	return '<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">'
	+'    <div class="modal-dialog" role="document">'
	+'        <div class="modal-content">'
	+'            <div class="modal-header text-center">'
	+'                <h4 class="modal-title w-100 font-weight-bold">댓글을 수정하세요</h4>'
	+'                <button type="button" class="close" data-dismiss="modal" aria-label="Close">'
	+'                    <span aria-hidden="true">&times;</span>'
	+'                </button>'
	+'            </div>'
	+'            <div class="modal-body mx-3">'
	+'                <div class="md-form mb-5">'
	+'                    <i class="fa fa-user prefix grey-text"></i>'
	+'                    <input type="text" id="form34" class="form-control validate">'
	+'                    <label data-error="wrong" data-success="right" for="form34">비밀번호</label>'
	+'                </div>'
	+''
	+'                <div class="md-form">'
	+'                    <i class="fa fa-pencil prefix grey-text"></i>'
	+'                    <textarea  type="text" id="form8" class="md-textarea form-control" rows="6"></textarea>'
	+'                    <label data-error="wrong" data-success="right" for="form8">수정할 댓글내용</label>'
	+'                </div>'
	+''
	+'            </div>'
	+'            <div class="modal-footer d-flex justify-content-center">'
	+'                <button class="btn btn-warning" href="localhost:8080/web/">수정 </button>'//.click(e=>{$.magnificPopup.close();})  <i class="fa fa-paper-plane-o ml-1"></i>
	+'            </div>'
	+'        </div>'
	+'    </div>'
	+'</div>';
}

function y_item_cDelUI(){
	return '<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">'
	+'    <div class="modal-dialog" role="document">'
	+'        <div class="modal-content">'
	+'            <div class="modal-header text-center">'
	+'                <h4 class="modal-title w-100 font-weight-bold">댓글삭제시 비밀번호가 필요합니다</h4>'
	+'                <button type="button" class="close" data-dismiss="modal" aria-label="Close">'
	+'                    <span aria-hidden="true">&times;</span>'
	+'                </button>'
	+'            </div>'
	+'            <div class="modal-body mx-3">'
	+'                <div class="md-form mb-5">'
	+'                    <i class="fa fa-user prefix grey-text"></i>'
	+'                    <input type="text" id="form34" class="form-control validate password">'
	+'                    <label data-error="wrong" data-success="right" for="form34">비밀번호</label>'
	+'                </div>'
	+'            </div>'
	+'            <div class="modal-footer d-flex justify-content-center">'
	+'                <button class="btn btn-warning" href="localhost:8080/web/">삭제 </button>'//.click(e=>{$.magnificPopup.close();}) 
	+'            </div>'
	+'        </div>'
	+'    </div>'
	+'</div>';
}
