function y_item_detailUI(x){
	return '<!--Carousel Wrapper-->'
	+'<div id="carousel-with-lb'+x+'" class="container carousel slide carousel-multi-item" data-ride="carousel">'
	+''
	+'  <!--Controls-->'
	+'  <div class="text-center controls-bottom">'
	+'    <a class="btn-floating text-left" href="#carousel-with-lb'+x+'" data-slide="prev"><i class="fa fa-chevron-left"></i></a>'
	+'    <a class="btn-floating text-right" href="#carousel-with-lb'+x+'" data-slide="next"><i class="fa fa-chevron-right"></i></a>'
	+'  </div>'
	+'  <!--/.Controls-->'
	+''
	+'  <!--Indicators-->'
	+'  <ol class="carousel-indicators">'
	+'    <li data-target="#carousel-with-lb'+x+'" data-slide-to="0" class="active first-color"></li>'
	+'    <li data-target="#carousel-with-lb'+x+'" data-slide-to="1" class="first-color"></li>'
	+'    <li data-target="#carousel-with-lb'+x+'" data-slide-to="2" class="first-color"></li>'
	+'  </ol>'
	+'  <!--/.Indicators-->'
	+''
	+'  <!--Slides and lightbox-->'
	+''
	+'  <div class="carousel-inner mdb-lightbox" role="listbox">'
	+'    <div id="mdb-lightbox-ui"></div>'
	+'    <!--First slide-->'
	+'    <div class="carousel-item active text-center">'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y ">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image1.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y ">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image2.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image3.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image4.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image5.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'

	+''
	+'    </div>'
	+'    <!--/.First slide-->'
	+''
	+'    <!--Second slide-->'
	+'    <div class="carousel-item text-center">'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image6.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image7.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image8.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image9.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="/web/resources/img/cmm/image10.jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'

	+''
	+'    </div>'
	+'    <!--/.Second slide-->'
	+''
	+'    <!--Third slide-->'
	+'    <div class="carousel-item text-center">'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(44).jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(45).jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(66).jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+''
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(53).jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'
	+'      <figure class="col-md-2 d-md-inline-block y">'
	+'        <a href="#y_item_detailUI" data-size="1600x1067">'
	+'          <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(56).jpg" class="img-fluid rounded">'
	+'        </a>'
	+'      </figure>'

	+''
	+'    </div>'
	+'    <!--/.Third slide-->'
	+''
	+'  </div>'
	+'  <!--/.Slides-->'
	+''
	+'</div>'
	+'<!--/.Carousel Wrapper-->'
}
