function y_item_detailUI(){
	return '<div class="accordion md-accordion accordion-blocks" id="accordionEx78" role="tablist" aria-multiselectable="true">'
	+'        <!-- Accordion card -->'
	+'        <div class="card" >'
	+''
	+'            <!-- Card header -->'
	+'            <div class="card-header" role="tab" id="headingUnfiled">'
	+''
	+'                <!--Options-->'
	+'                <div class="dropdown pull-left">'
	                    +'<button class="btn btn-info btn-sm m-0 mr-3 p-2 dropdown-toggle waves-effect waves-light" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-pencil"></i>'
	+'                                                            </button>'
	+'                    <div class="dropdown-menu dropdown-info">'
	+'                        <a class="dropdown-item" href="#">Add new condition</a>'
	+'                        <a class="dropdown-item" href="#">Rename folder</a>'
	+'                        <a class="dropdown-item" href="#">Delete folder</a>'
	+'                    </div>'
	+'                </div>'
	+''
	+'                <!-- Heading -->'
	                +'<a data-toggle="collapse" data-parent="#accordionEx78" href="#collapseUnfiled" aria-expanded="false" aria-controls="collapseUnfiled" class="collapsed">'
	+'                    <h5 class="mt-1 mb-0">'
	+'                        <span>Unfiled items</span>'
	+'                        <i class="fa fa-angle-down rotate-icon"></i>'
	+'                    </h5>'
	+'                </a>'
	+''
	+'            </div>'
	+''
	+'            <!-- Card body -->'
	+'            <div id="collapseUnfiled" class="collapse" role="tabpanel" aria-labelledby="headingUnfiled" data-parent="#accordionEx78" style="">'
	+'                <div class="card-body">'
	+''
	+'                    <!--Top Table UI-->'
	+'                    <div class="table-ui p-2 mb-3 mx-3 mb-4">'
	+''
	+'                        <!--Grid row-->'
	+'                        <div class="row">'
	+''
	+'                            <!--Grid column-->'
	+'                            <div class="col-xl-4 col-lg-6 col-md-12">'
	+''
	+'                                <!--Name-->'
	                                +'<div class="select-wrapper mdb-select colorful-select dropdown-info mx-2"><span class="caret">▼</span><input type="text" class="select-dropdown" readonly="true" data-activates="select-options-b32783ea-7c79-4f3e-813b-010715af3552" value=""><ul id="select-options-b32783ea-7c79-4f3e-813b-010715af3552" class="dropdown-content select-dropdown w-100"><li class="disabled active"><span class="filtrable">  Bulk actions</span></li><li class=" "><span class="filtrable">  Delete</span></li><li class=" "><span class="filtrable">  Change folder</span></li></ul><select class="mdb-select colorful-select dropdown-info mx-2 initialized">'
	+'                                    <option value="" disabled="" selected="">Bulk actions</option>'
	+'                                    <option value="1">Delete</option>'
	+'                                    <option value="2">Change folder</option>'
	+'                                </select></div>'
	+''
	+'                            </div>'
	+'                            <!--Grid column-->'
	+''
	+'                            <!--Grid column-->'
	+'                            <div class="col-xl-4 col-lg-6 col-md-6">'
	+''
	+'                                <!--Blue select-->'
	                                +'<div class="select-wrapper mdb-select colorful-select dropdown-info mx-2"><span class="caret">▼</span><input type="text" class="select-dropdown" readonly="true" data-activates="select-options-25ba7f64-8ac8-4b70-b594-e02af19d0628" value=""><ul id="select-options-25ba7f64-8ac8-4b70-b594-e02af19d0628" class="dropdown-content select-dropdown w-100"><li class="disabled "><span class="filtrable">  Show only</span></li><li class="active"><span class="filtrable">  All  (2000)</span></li><li class=" "><span class="filtrable">  Clicks  (200)</span></li><li class=" "><span class="filtrable">  Page  (1800)</span></li><li class=" "><span class="filtrable">  Scroll  (200)</span></li><li class=" "><span class="filtrable">  Forms  (50)</span></li><li class=" "><span class="filtrable">  Time  (50)</span></li><li class=" "><span class="filtrable">  UTM  (50)</span></li></ul><select class="mdb-select colorful-select dropdown-info mx-2 initialized">'
	+'                                    <option value="" disabled="">Show only</option>'
	+'                                    <option value="1" selected="">All  (2000)</option>'
	+'                                    <option value="2">Clicks  (200)</option>'
	+'                                    <option value="3">Page  (1800)</option>'
	+'                                    <option value="4">Scroll  (200)</option>'
	+'                                    <option value="5">Forms  (50)</option>'
	+'                                    <option value="6">Time  (50)</option>'
	+'                                    <option value="7">UTM  (50)</option>'
	+'                                </select></div>'
	+'                                <!--/Blue select-->'
	+''
	+'                            </div>'
	+'                            <!--Grid column-->'
	+''
	+'                            <!--Grid column-->'
	+'                            <div class="col-xl-4 col-lg-6 col-md-6">'
	+''
	+'                                <!--Blue select-->'
	                                +'<div class="select-wrapper mdb-select colorful-select dropdown-info mx-2"><span class="caret">▼</span><input type="text" class="select-dropdown" readonly="true" data-activates="select-options-1eec669f-2bc6-4c73-b117-c22e84d8a1b5" value=""><ul id="select-options-1eec669f-2bc6-4c73-b117-c22e84d8a1b5" class="dropdown-content select-dropdown w-100"><li class="disabled active"><span class="filtrable">  Filter</span></li><li class=" "><span class="filtrable">  All  (100)</span></li><li class=" "><span class="filtrable">  Active  (2000)</span></li><li class=" "><span class="filtrable">  Inactive  (1000)</span></li></ul><select class="mdb-select colorful-select dropdown-info mx-2 initialized">'
	+'                                    <option value="" disabled="" selected="">Filter</option>'
	+'                                    <option value="1">All  (100)</option>'
	+'                                    <option value="1">Active  (2000)</option>'
	+'                                    <option value="2">Inactive  (1000)</option>'
	+'                                </select></div>'
	+'                                <!--/Blue select-->'
	+''
	+'                            </div>'
	+'                            <!--Grid column-->'
	+''
	+'                        </div>'
	+'                        <!--Grid row-->'
	+''
	+'                    </div>'
	+'                    <!--Top Table UI-->'
	+''
	+'                    <!-- Table responsive wrapper -->'
	+'                    <div class="table-responsive mx-3">'
	+'                        <!--Table-->'
	+'                        <table class="table table-hover mb-0">'
	+''
	+'                            <!--Table head-->'
	+'                            <thead>'
	+'                                <tr>'
	+'                                    <th>'
	+'                                        <input class="form-check-input" type="checkbox" id="checkbox">'
	+'                                        <label for="checkbox" class="mr-2 label-table"></label>'
	+'                                    </th>'
	+'                                    <th class="th-lg"><a>Name <i class="fa fa-sort ml-1"></i></a></th>'
	+'                                    <th class="th-lg"><a>Condition<i class="fa fa-sort ml-1"></i></a></th>'
	+'                                    <th class="th-lg"><a>Last edited<i class="fa fa-sort ml-1"></i></a></th>'
	+'                                    <th></th>'
	+'                                </tr>'
	+'                            </thead>'
	+'                            <!--Table head-->'
	+''
	+'                            <!--Table body-->'
	+'                            <tbody>'
	+'                                <tr>'
	+'                                    <th scope="row">'
	+'                                        <input class="form-check-input" type="checkbox" id="checkbox1">'
	+'                                        <label for="checkbox1" class="label-table"></label>'
	+'                                    </th>'
	+'                                    <td>Test subscription</td>'
	+'                                    <td><code>Scroll %</code> equals or greater than <strong>80</strong></td>'
	+'                                    <td>12.06.2017</td>'
	+'                                    <td>'
	                                        +'<a><i class="fa fa-info mx-1" data-toggle="tooltip" data-placement="top" title="" data-original-title="Tooltip on top"></i></a>'
	+'                                        <a><i class="fa fa-pencil-square mx-1"></i></a>'
	+'                                        <a><i class="fa fa-times mx-1"></i></a>'
	+'                                    </td>'
	+'                                </tr>'
	+'                                <tr>'
	+'                                    <th scope="row">'
	+'                                        <input class="form-check-input" type="checkbox" id="checkbox2">'
	+'                                        <label for="checkbox2" class="label-table"></label>'
	+'                                    </th>'
	+'                                    <td>Product Hunt Visitor</td>'
	+'                                    <td><code>Scroll %</code> equals or greater than <strong>80</strong></td>'
	+'                                    <td>13.06.2017</td>'
	+'                                    <td>'
	                                        +'<a><i class="fa fa-info mx-1" data-toggle="tooltip" data-placement="top" title="" data-original-title="Tooltip on top"></i></a>'
	+'                                        <a><i class="fa fa-pencil-square mx-1"></i></a>'
	+'                                        <a><i class="fa fa-times mx-1"></i></a>'
	+'                                    </td>'
	+'                                </tr>'
	+'                                <tr>'
	+'                                    <th scope="row">'
	+'                                        <input class="form-check-input" type="checkbox" id="checkbox3">'
	+'                                        <label for="checkbox3" class="label-table"></label>'
	+'                                    </th>'
	+'                                    <td>Test subscription</td>'
	+'                                    <td><code>Scroll %</code> equals or greater than <strong>80</strong></td>'
	+'                                    <td>12.06.2017</td>'
	+'                                    <td>'
	                                        +'<a><i class="fa fa-info mx-1" data-toggle="tooltip" data-placement="top" title="" data-original-title="Tooltip on top"></i></a>'
	+'                                        <a><i class="fa fa-pencil-square mx-1"></i></a>'
	+'                                        <a><i class="fa fa-times mx-1"></i></a>'
	+'                                    </td>'
	+'                                </tr>'
	+'                            </tbody>'
	+'                            <!--Table body-->'
	+'                        </table>'
	+'                        <!--Table-->'
	+'                    </div>'
	+'                    <!-- Table responsive wrapper -->'
	+''
	+'                </div>'
	+'            </div>'
	+'        </div>'
	+'        <!-- Accordion card -->'
	+'</div>';
}

