"use strict"
function y_item_cMdfUI(){
	return '<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">'
	+'    <div class="modal-dialog" role="document">'
	+'        <div class="modal-content">'
	+'            <div class="modal-header text-center">'
	+'                <h4 class="modal-title w-100 font-weight-bold">댓글을 수정하세요</h4>'
	+'                <button type="button" class="close" data-dismiss="modal" aria-label="Close">'
	+'                    <span aria-hidden="true">&times;</span>'
	+'                </button>'
	+'            </div>'
	+'            <div class="modal-body mx-3">'
	+'                <div class="md-form mb-5">'
	+'                    <i class="fa fa-user prefix grey-text"></i>'
	+'                    <input type="text" id="form34" class="form-control validate">'
	+'                    <label data-error="wrong" data-success="right" for="form34">비밀번호</label>'
	+'                </div>'
	+''
	+'                <div class="md-form">'
	+'                    <i class="fa fa-pencil prefix grey-text"></i>'
	+'                    <textarea  type="text" id="form8" class="md-textarea form-control" rows="6"></textarea>'
	+'                    <label data-error="wrong" data-success="right" for="form8">수정할 댓글내용</label>'
	+'                </div>'
	+''
	+'            </div>'
	+'            <div class="modal-footer d-flex justify-content-center">'
	+'                <button class="btn btn-warning" href="localhost:8080/web/">수정 </button>'//.click(e=>{$.magnificPopup.close();})  <i class="fa fa-paper-plane-o ml-1"></i>
	+'            </div>'
	+'        </div>'
	+'    </div>'
	+'</div>';
}

function y_item_cDelUI(){
	return '<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">'
	+'    <div class="modal-dialog" role="document">'
	+'        <div class="modal-content">'
	+'            <div class="modal-header text-center">'
	+'                <h4 class="modal-title w-100 font-weight-bold">댓글삭제시 비밀번호가 필요합니다</h4>'
	+'                <button type="button" class="close" data-dismiss="modal" aria-label="Close">'
	+'                    <span aria-hidden="true">&times;</span>'
	+'                </button>'
	+'            </div>'
	+'            <div class="modal-body mx-3">'
	+'                <div class="md-form mb-5">'
	+'                    <i class="fa fa-user prefix grey-text"></i>'
	+'                    <input type="text" id="form34" class="form-control validate password">'
	+'                    <label data-error="wrong" data-success="right" for="form34">비밀번호</label>'
	+'                </div>'
	+'            </div>'
	+'            <div class="modal-footer d-flex justify-content-center">'
	+'                <button class="btn btn-warning" href="localhost:8080/web/">삭제 </button>'//.click(e=>{$.magnificPopup.close();}) 
	+'            </div>'
	+'        </div>'
	+'    </div>'
	+'</div>';
}
