function modifyUI(){
	return '<div id="memberModify">'
    +'<form id="memberModify">'
    +'<h2>마이페이지</h2>'
        +'<div class="container">'
            +'<hr>'
        +'<label for="member_id"><b>아이디</b></label>'
        +'<input type="text" name="member_id" value="아이디표시" readonly><br>'
        +'<label for="password"><b>비밀번호</b></label>'
        +'<input type="text" name="password" value="비밀번호표시" required><br>'
        +'<label for="name"><b>이름</b></label>'
        +'<input type="text" name="name" value="이름" readonly><br>'
        +'<label for="ssn"><b>주민번호</b></label>'
        +'<input type="text" name="ssn" value="주민번호" readonly><br>'
        +'<label for="address"><b>주소</b></label>'
        +'<input type="text"  name="address" value="주소" required><br>'
        +'<label for="e_mail"><b>이메일 주소</b></label>'
        +'<input type="text" name="e_mail" value="이메일 표시" required><br>'
        +'<label for="phone_num"><b>전화번호</b></label>'
        +'<input type="text" name="phone_num" value="니 저나뻐노" required><br>'

        +'<div class="clearfix">'
        +'<button type="submit" id="modify_submit_btn" class="modify_submit_btn">정보수정</button>'
        +'</div>'
        +'</div>'
    +'</form>'
    +'</div>'
}
