function y_item_detailUI(){
	return '<div class="white-popup text-center" id="y_item_detailUI">'
	+'<div class="detail-main">    '/*white-popup*/
	+'   <div class="row content">'
	+'      <div class="col-sm-8 text-left"> '
	+'         <div class="container">'
	+'            <br/><br/><br/><br/>     '
	+'            <img src="/web/resources/img/yoonho/maehwa_chicken.jpg" class="img-rounded item img"> '
	+'            <h1>매화 (치킨, 연어구이)</h1>'
	            +'<p>[베스트 & 스테디셀러 SINCE 2007] 12가지 다양한 반찬으로 구성된 프리미엄 도시락입니다. 푸짐한 반찬과 함께 촉촉하고 부드러운 연어구이와 치킨이 구성되어 있어 부족하지 않고 든든하게 드실 수 있는 도시락 입니다. 생수와 조미 김이 함께 제공 됩니다.</p>'
	+'           <br/> '
	+'           <hr>'
	+'           <br/><br/><br/>'
	+'				<!-- Comment Area Start -->'
	+'              <div class="comment_area section_padding_50 clearfix">'
	+'                <h4 class="mb-30">2개의 댓글이 작성되었습니다.</h4><br/><br/><br/>'
	+'                <ol>'
	+'                  <!-- Single Comment Area -->'
	+'                  <li class="single_comment_area">'
	+'                    <div class="comment-wrapper d-flex">'
	+'                      <!-- Comment Meta -->'
	+'                      <div class="comment-author">'
	+'                        <img src="/web/resources/img/yoonho/img_avatar1.png" height="40" width="40" class="img-circle">'
	+'                      </div>'
	+'                      <!-- Comment Content -->'
	+'                      <div class="comment-content">'
	+'                        <br/>'
	+'                        <span class="comment-date text-muted">27 Aug 2018</span>'
	
	+'                        <h5>맛짱</h5>'
	+'                        <div>'
	+'                          <p><span class="glyphicon glyphicon-star"></span>'
	+'                            <span class="glyphicon glyphicon-star"></span>'
	+'                            <span class="glyphicon glyphicon-star-empty"></span>'
	+'                            <span class="glyphicon glyphicon-star-empty"></span>'
	+'                            <span class="glyphicon glyphicon-star-empty"></span></p>'
	+'                        </div>'
	+'                        <p>매화도시락 너무 비싸요 음식점에서 사먹는가격보다 비쌈.</p>'
	+'                          <span class="glyphicon glyphicon-thumbs-up"></span>'
	+'                        <a href="#" class="btn btn-warning" role="button">수정<a/>'
	                        +''
	+'                      </div>'
	+'                    </div>'
	+'                  </li>'
	+'           		<hr>'
	+'                  <li class="single_comment_area">'
	+'                    <div class="comment-wrapper d-flex">'
	+'                      <!-- Comment Meta -->'
	+'                      <div class="comment-author">'
	+'                        <img src="/web/resources/img/yoonho/img_avatar3.png" height="40" width="40" class="img-circle">'
	+'                      </div>'
	+'                      <!-- Comment Content -->'
	+'                      <div class="comment-content">'
	+'                        <br/>'
	+'                        <span class="comment-date text-muted">27 Aug 2018</span>'
	+'                        <h5>바빠바빠너무바빠</h5>'
	+'                        <div>'
	+'                          <p><span class="glyphicon glyphicon-star"></span>'
	+'                            <span class="glyphicon glyphicon-star"></span>'
	+'                            <span class="glyphicon glyphicon-star"></span>'
	+'                            <span class="glyphicon glyphicon-star"></span>'
	+'                            <span class="glyphicon glyphicon-star"></span></p>'
	     +''
	+'                        </div>'
	+'                        <p>바쁜 저녁 마라톤회의때 먹었는데 든든합니다. 강추!!</p>'
	+'                          <span class="glyphicon glyphicon-thumbs-up"></span>'
	+'                        <a href="#" class="btn btn-warning" role="button">신고<a/>'
	+'                      </div>'
	+'                    </div>'
	+'                  </li>'
	+'                </ol>'
	+'              </div>'
	            +''
	+'              <!-- Leave A Comment -->'
	+'              <div class="leave-comment-area section_padding_50 clearfix">'
	+'                <div class="comment-form">'
	+'                  <h4 class="mb-30">Comment</h4>'
	            +''
	+'                  <!-- Comment Form -->'
	+'                  <form action="#" method="post">'
	+'                    <div class="form-group">'
	                      +'<textarea class="form-control" name="message" id="message" cols="30" rows="10" placeholder="댓글을 입력하세요"></textarea>'
	+'                    </div>'
	+'                    <button type="submit" class="btn btn-warning">Post Comment</button>'
	+'                  </form>'
	+'                </div>'
	+'              </div>'
	+'			</div>'
	+'		</div>'
	+'	</div>'

	+'		<div class="detail-right position">'
	+'			<div class="well well-lg">'
	+'				<h2>매화 (치킨, 연어)</h2>'
	+'				<h3>(사각도시락)</h3>'
	+'				<p class="p float left">'
	+'					<span class="glyphicon glyphicon-star"></span>'
	+'					<span class="glyphicon glyphicon-star"></span>'
	+'					<span class="glyphicon glyphicon-star"></span>'
	+'					<span class="glyphicon glyphicon-star"></span>'
	+'					<span class="glyphicon glyphicon-star-empty"></span>'
	+'				</p>'
	+'				<br/>'
	+'				<p class="p float left">'
	+'					<span class="glyphicon glyphicon-thumbs-up p float left"></span>'
	+'				</p>'
	+'			</div>'
	+'		</div>'
	
	+'</div>'
	+'</div>'
	

	+'</div>'

	

}