function commentUI(){
	return '            <div class="panel-body">'
	+'                <ul class="list-group">'
	+'                    <li class="list-group-item">'
	+'                        <div class="row">'
	+'                            <div class="col-xs-2 col-md-1">'
	+'                                <img src="http://placehold.it/80" class="img-circle img-responsive" alt="" /></div>'
	+'                            <div class="col-xs-10 col-md-11">'
	+'                                <div>'
	+'                                   <div class="mic-info">'
	+'                                     <p><span class="glyphicon glyphicon-star pull-right"></span>'
	+'                                     <span class="glyphicon glyphicon-star pull-right"></span>'
	+'                                     <span class="glyphicon glyphicon-star pull-right"></span>'
	+'                                     <span class="glyphicon glyphicon-star pull-right"></span>'
	+'                                     <span class="glyphicon glyphicon-star pull-right"></span></p>'
	+'                                     글쓴이 <a href="#"> 김정훈 </a> 작성날짜'
	+'                                     '
	+'                                      <div class="action">'
	+'                                    <button id="edit_comment" style="background-color:#000000" type="button" class="j_commentbtn pull-right " title="삭제하기">'
	+'                                        <span class="glyphicon glyphicon-trash"></span>'
	+'                                    </button>'
	+'                                    <button id="report_comment" style="background-color:#ff0000" type="button" class="j_commentbtn pull-right" title="신고하기">'
	+'                                        <span class="glyphicon glyphicon-bullhorn"></span>'
	+'                                    </button>'
	+'                                    <button id="respect_comment" style="background-color:#00cc00" type="button" class="j_commentbtn pull-right" title="추천하기">'
	+'                                        <span class="glyphicon glyphicon-thumbs-up"></span>'
	+'                                    </button>'
	+'                                    <button id="respect_comment" style="background-color:#cc66ff" type="button" class="j_commentbtn pull-right" title="수정하기">'
	+'                                        <span class="glyphicon glyphicon-pencil"></span>'
	+'                                    </button>'
	+'                                </div>'
	+'                                  </div>'
	+'                                </div>'
	+'                                <div class="comment-text">'
	+'                                  동해물과 백두산이 마르고 닳도록 하느님이 보우하사 우리나라만세 무궁화 삼천리 화려강산 대한사람 대한으로 길이 보전하세'
	+'                                </div>'
	+'                              '
	+'                            </div>'

	+'                    </li>'

	+'  <div class="md-form amber-textarea active-amber-textarea-2">'
	+'   <textarea type="text" id="textarea" class="md-textarea form-control" rows="3"></textarea>'
	+'<button id="submit_comment" type="button" class="j_commentbtn pull-right">'
	+'<span class="glyphicon glyphicon-pencil"></span></button>'
	+'  </div> '

	


}