function naviUI (){
	return '<nav class="navbar navbar-default">'
	+'<div class="container-fluid">'
		+'<div class="navbar-header">'
			+'<button type="button" class="navbar-toggle collapsed"'
				+'data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">'
				+'<span class="sr-only">Toggle navigation</span> <span'
					+'class="icon-bar"></span> <span class="icon-bar"></span> <span'
					+'class="icon-bar"></span>'
			+'</button>'
			+'<a class="navbar-brand" href="#" id="logo">Be meal</a>'
		+'</div>'
		+'<div class="collapse navbar-collapse"'
			+'id="bs-example-navbar-collapse-1">'
			+'<ul class="nav navbar-nav">'
				+'<li><a href="#" id="menu"> MENU </a></li>'
				+'<li><a href="#" id="join">JOIN '
						+'</a></li>'
				+'<li><a href="#" id="taste">MY TASTE</a></li>'
				+'<li><a href="#" id="evaluate">평가하기</a></li>'
				+'<li><a href="#" id="sam">SAM</a></li>'
				+'</ul>'
			+'<ul class="nav navbar-nav navbar-right">'
				+'<li class="dropdown">'
					+'<a href="#" class="dropdown-toggle"'
						+'data-toggle="dropdown" role="button" aria-expanded="false"> <span class="glyphicon glyphicon-user"></span> <span class="caret"></span>'
					+'</a>'
					+'<ul id="info" class="dropdown-menu" role="menu">'
						+'<li><a href="#" id="login">로그인</a></li>'
					+'</ul>'
				+'</li>'
			+'</ul>'
			+'<form class="navbar-form navbar-right" role="search">'
				+'<div class="form-group">'
					+'<input type="text" class="form-control" placeholder="Search">'
				+'</div>'
				+'<button type="submit" class="btn btn-default">'
					+'<span class="glyphicon glyphicon-search"></span>'
				+'</button>'
			+'</form>'
		+'</div>'
	+'</div>'
+'</nav>'
};