function y_item_detail_modalUI(){
	return '<div class="yh-mfp-wrap yh-white-popup" id="y_item_detailUI">'
	+'	<div class="col-sm-12 yh-mfp-container detail-main text-center">     '
	+'	   	<div class="col-sm-8 mgt50-mgba yh-mfp-content text-left"  > '
	+'         	<div margin ="0 auto;"> '
	+'	    		<div class="col-lg-12">'
	+'				    <span class="col-lg-5 text-center" style="margin-top:70px;">'
	+'						<img src="/web/resources/img/yoonho/maehwa_chicken.jpg"  height="80%" width="80%" margin="20px auto" class="img-rounded"> '
	+'				    </span >'
	+'				    <span class="col-lg-6 mgt50">'
	+'						<div class="col-lg-8 mgt50-mgb100" style="background-color:#f1f1f1; "><!-- border:1px solid #444444;-->'
	+'							<h2>Clickable Dropdown</h2>'
	+'							<p>Click on the button to open the dropdown menu.</p>'
	+''
	+'							<div class="dropdown">'
	+'								<button onclick="myFunction()" class="dropbtn">같은 종류의 도시락</button>'
	+'								<div id="myDropdown" class="dropdown-content">'
	+'									<a href="#home">같은 종류의 도시락</a>'
	+'									<a href="#about">20대가 많이 산 도시락</a>'
	+'									<a href="#contact">이달의 도시락</a>'
	+'								</div>'
	+'							</div>'
	+''
	+'						</div>'
	+'					</span>'
	+'	    		</div>'
	+'	    	</div>'
	+'			<!-- Comment Area Start -->'
	+'			<div class="col-lg-8 mgt50-mgb100" >'
	+'                <h4>2개의 댓글이 작성되었습니다.</h4>'
	+''
	+'				<!-- Single Comment Area -->'
	+''
	+'                <div class="single_comment_area">'
	        	+''
	+'                	<!-- Comment Meta -->'
	+'                	<div class="col-lg-8" style="width:10%; height:20%;">'
	+'                    	<img src="/web/resources/img/yoonho/img_avatar1.png" style="height:40px; width:40px" class="img-circle">'
	+'                	</div>'
	+''
	+'                	<!-- Comment Content -->'
	+'                	<div>'
	+'                        <div class="text-muted">27 Aug 2018</div>'
	+'                        <h5>맛짱</h5>'
	+'                        <div>'
	+''
	+'							<!-- rating star -->'
	+'							<span class="star-input">'
	+'								<span class="input">'
	+'									<input type="radio" name="star-input" id="p1" value="1"><label for="p1">1</label>'
	+'									<input type="radio" name="star-input" id="p2" value="2"><label for="p2">2</label>'
	+'									<input type="radio" name="star-input" id="p3" value="3"><label for="p3">3</label>'
	+'									<input type="radio" name="star-input" id="p4" value="4"><label for="p4">4</label>'
	+'									<input type="radio" name="star-input" id="p5" value="5"><label for="p5">5</label>'
	+'									<input type="radio" name="star-input" id="p6" value="6"><label for="p6">6</label>'
	+'									<input type="radio" name="star-input" id="p7" value="7"><label for="p7">7</label>'
	+'									<input type="radio" name="star-input" id="p8" value="8"><label for="p8">8</label>'
	+'									<input type="radio" name="star-input" id="p9" value="9"><label for="p9">9</label>'
	+'									<input type="radio" name="star-input" id="p10" value="10"><label for="p10">10</label>'
	+'								</span>'
	+'								<output for="star-input"><b>0</b>점</output>'
	+'							</span>'
	                        +''
	+'                        </div>'
	+'                        <div >'
	+'							<p>매화도시락 너무 비싸요 음식점에서 사먹는가격보다 비쌈..</p>'
	+'                        	<i role="button" style = "font-size:48px;" class="fa fa-thumbs-o-up"></i>'
	+'                        	<a href="#" class="btn btn-warning" role="button">수정</a>'
	+'						</div>'
	+'                	</div>'
	+''
	+'                </div>'
	+''
	+''
	+'	   			<!-- Single Comment Area 2 -->'
	+''
	+'		    	<div class="col-lg-8 mgt50-mgb100">'
	+''
	+'		          	<!-- Comment Meta -->'
	+'		          	<span >'
	+'		        		<img src="/web/resources/img/yoonho/img_avatar3.png" height="40" width="40" class="img-circle">'
	+'		      		</span>'
	+'		            <!-- Comment Content -->'
	+'		            <div>'
	+'		                <span class="text-muted">27 Aug 2018</span>'
	+'		                <h5>바빠바빠너무바빠</h5>'
	+'		                <div>'
	+''
	+'							<!-- rating star -->'
	+'							<span class="star-input">'
	+'								<span class="input">'
	+'									<input type="radio" name="star-input" id="p1" value="1"><label for="p1">1</label>'
	+'									<input type="radio" name="star-input" id="p2" value="2"><label for="p2">2</label>'
	+'									<input type="radio" name="star-input" id="p3" value="3"><label for="p3">3</label>'
	+'									<input type="radio" name="star-input" id="p4" value="4"><label for="p4">4</label>'
	+'									<input type="radio" name="star-input" id="p5" value="5"><label for="p5">5</label>'
	+'									<input type="radio" name="star-input" id="p6" value="6"><label for="p6">6</label>'
	+'									<input type="radio" name="star-input" id="p7" value="7"><label for="p7">7</label>'
	+'									<input type="radio" name="star-input" id="p8" value="8"><label for="p8">8</label>'
	+'									<input type="radio" name="star-input" id="p9" value="9"><label for="p9">9</label>'
	+'									<input type="radio" name="star-input" id="p10" value="10"><label for="p10">10</label>'
	+'								</span>'
	+'								<output for="star-input"><b>0</b>점</output>'
	+'							</span>'
	+''
	+'		        		</div>'
	+'		        		<div>'
	+'		            		<p>바쁜 저녁 마라톤회의때 먹었는데 든든합니다. 강추!!</p>'
	+'		              		<span class="glyphicon glyphicon-thumbs-up"></span>'
	+'		            		<a href="#" class="btn btn-warning" role="button">신고<a/>'
	+'		  				</div>'
	+'		  			</div>'
	+''
	+'	        	</div>'
	+''
	+'			</div>'
	+''
	+'	      	<!-- Leave A Comment -->'
	+'	      	<div class="col-lg-8 mgt50-mgb100">'
	+'	            <div>'
	+'	              	<h3>Comment</h3>'
	+''
	+'	              	<!-- Comment Form -->'
	+'	              	<form action="#" method="post">'
	+'	                	<div class="comment-testbox">'
	+'	                  		<textarea class="comment-testbox" name="message" id="message" cols="30" rows="10" placeholder="댓글을 입력하세요"></textarea>'
	+'	                	</div>'
	+'	                	<button type="submit" class="btn btn-warning">Post Comment</button>'
	+'	              	</form>'
	+''
	+'	            </div>'
	+'			</div>'
	+'		</div>'
	+'	</div>'
		+''
	+'	<!-- detail right yh-mfp-navi -->'
	+'	<div class="col-sm-5 mg0-pd0 detail-right yh-mfp-navi">'//
	+'		<!-- item fixed navi UI -->'
	+'		<div class="container-fluid">'
	+'		    <div class="row">'
	+'				<div class="col-lg-12" style="background-color:#f1f1f1;"><!-- border:1px solid #444444;-->'
	+'					<h1 class="text-center">매화 (치킨, 연어구이)</h1>'
	+'					<p class="text-center">사각 도시락</p>'
	+'					<!-- rating star -->'
	+'					<span class="star-input">'
	+'						<span class="input">'
	+'							<input type="radio" name="star-input" id="p1" value="1"><label for="p1">1</label>'
	+'							<input type="radio" name="star-input" id="p2" value="2"><label for="p2">2</label>'
	+'							<input type="radio" name="star-input" id="p3" value="3"><label for="p3">3</label>'
	+'							<input type="radio" name="star-input" id="p4" value="4"><label for="p4">4</label>'
	+'							<input type="radio" name="star-input" id="p5" value="5"><label for="p5">5</label>'
	+'							<input type="radio" name="star-input" id="p6" value="6"><label for="p6">6</label>'
	+'							<input type="radio" name="star-input" id="p7" value="7"><label for="p7">7</label>'
	+'							<input type="radio" name="star-input" id="p8" value="8"><label for="p8">8</label>'
	+'							<input type="radio" name="star-input" id="p9" value="9"><label for="p9">9</label>'
	+'							<input type="radio" name="star-input" id="p10" value="10"><label for="p10">10</label>'
	+'						</span>'
	+'						<output for="star-input"><b>0</b>점</output>'
	+'					</span>'
	+'			 			<p class="text-left">1520명이 평가했어요</p>'
	+'					<p role="button" class="glyphicon glyphicon-thumbs-up" >(743명)</p>'
	+'				</div>'
	+'			</div>'
	+'			<div class="row">'
	+''
	+'				<div class="col-lg-12" style="background-color:beige;"><!-- border:1px solid #444444;-->'
	+'					<table class="table">'
	+'						<tbody>'
	+'						<tr>'
	+'							<td class="text-left">'
	+'								<h5>업  체</h5>'
	+'							</td>'
	+'							<td class="text-right">'
	+'								<h5>오봉도시락</h5>'
	+'							</td>'
	+'						</tr>'
	+'						<tr>'
	+'							<td class="text-left">'
	+'								<h5>칼로리</h5>'
	+'							</td>'
	+'							<td class="text-right">'
	+'								<h5>405.5Kcal</h5>'
	+'							</td>'
	+'						</tr>'
	+'						<tr>'
	+'							<td class="text-left">'
	+'								<h5>가  격</h5>'
	+'							</td>'
	+'							<td class="text-right">'
	+'								<h5>10,000 원</h5>'
	+'							</td>'
	+'						</tr>'
	+'						<tr>'
	+'							<td class="text-left">'
	+'								<h5>알러지 정보</h5>'
	+'							</td>'
	+'						</tr>'
	+'						<tr>'
	+'							<td class="text-left">'
	+'								<img src="/web/resources/img/yoonho/maehwa_chicken.jpg" class="img-rounded" height="70" width="70">'
	+'							</td>'
	+'							<td class="text-left">'
	+'								<p role="button" class="text-right">#고소</p>'
	+'								<p role="button" class="text-right">#달콤</p>'
	+'							</td>'
	+'						</tr>'
	+'						</tbody>'
	+'					</table>'
	+'					<hr/>'
	+'					<p class="text-left">'
							    +'베스트 & 스테디셀러 SINCE 2007] 12가지 다양한 반찬으로 구성된 프리미엄 도시락입니다. 푸짐한 반찬과 함께 촉촉하고 부드러운 연어구이와 치킨이 구성되어 있어 부족하지 않고 든든하게 드실 수 있는 도시락 입니다. 생수와 조미 김이 함께 제공 됩니다.'
	+'					</p>'
	+'				</div>'
	+'	    	</div>'
	+'	    </div>'
	+'	</div>'
	+'</div>'
	+''
	+'</div>'
	+'	<!-- JS script yoonho.js에 추가하고 script 지울것 -->'
	+'<script>'
	+'/* When the user clicks on the button, toggle between hiding and showing the dropdown content */'
	+'function myFunction() {'
	+'    document.getElementById("myDropdown").classList.toggle("show");'
	+'}'
	+''
	+'// Close the dropdown if the user clicks outside of it'
	+'window.onclick = function(event) {'
	+'	if (!event.target.matches(".dropbtn")) {'
	+''
	+'		var dropdowns = document.getElementsByClassName("dropdown-content");'
	+'		var i;'
	+'		for (i = 0; i < dropdowns.length; i++) {'
	+'			var openDropdown = dropdowns[i];'
	+'			if (openDropdown.classList.contains("show")) {'
	+'				openDropdown.classList.remove("show");'
	+'			}'
	+'		}'
	+'	}	'
	+'}'
	+'	/* When the user clicks on the button, Star is rated*/'
	+'	var starRating = function(){'
	+'		var $star = $(".star-input"),'
	+'			$result = $star.find("output>b");'
	+'		$(document)'
	+'		.on("focusin", ".star-input>.input", function(){'
	+'			$(this).addClass("focus");'
	+'		})'
	+'		.on("focusout", ".star-input>.input", function(){'
	+'			var $this = $(this);'
	+'			setTimeout(function(){'
	+'				if($this.find(":focus").length === 0){'
	+'					$this.removeClass("focus");'
	+'				}'
	+'			}, 100);'
	+'		})'
	+'		.on("change", ".star-input :radio", function(){'
	+'			$result.text($(this).next().text());'
	+'		})'
	+'		.on("mouseover", ".star-input label", function(){'
	+'			$result.text($(this).text());'
	+'		})'
	+'		.on("mouseleave", ".star-input>.input", function(){'
	+'			var $checked = $star.find(":checked");'
	+'			if($checked.length === 0){'
	+'				$result.text("0");'
	+'			} else {'
	+'				$result.text($checked.next().text());'
	+'			}'
	+'		});'
	+'	};'
	+'	starRating();'
	+'</script>'

;


}